services:
  - type: web
    name: pharmaguard-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
